server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: rental
          uri: http://localhost:8081
          predicates:
            - Path=/rentals/** 
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/** 
        - id: mypage
          uri: http://localhost:8083
          predicates:
            - Path= /mypages/**
        - id: book
          uri: http://localhost:8084
          predicates:
            - Path=/books/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rental
          uri: http://user10-rental:8080
          predicates:
            - Path=/rentals/** 
        - id: payment
          uri: http://user10-payment:8080
          predicates:
            - Path=/payments/** 
        - id: mypage
          uri: http://user10-mypage:8080
          predicates:
            - Path= /mypages/**
        - id: book
          uri: http://user10-book:8080
          predicates:
            - Path=/books/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
